# Name of your application. Used to uniquely configure containers.
service: discover

# Name of the container image.
image: dielume/kamal

# Deploy to these servers.
servers:
  web:
    hosts: 146.190.149.32
    options:
      network: 'kamal_network'
    labels:
      traefik.http.routers.discover.rule: Host(`prueba.kamal.website`)
      traefik.http.routers.discover.tls: true
      traefik.http.routers.discover.tls.certresolver: letsencrypt

# Credentials for your image host.
registry:
  username: dielume
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true
    PT_SILENCE_AR_COMPAT_WARNING: true
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - DB_HOST
